
---
title: "About"
---

I would like to share some interesting facts about myself- I am a classical singer of the Hindustani (Gwalior) Gharana and a polyglot, with proficiency in four languages and basic conversational skills in two others. The process of learning each has taught me the virtues of hard work and perseverance, especially because of the intensive training involved. I have also been part of various initiatives for providing basic education to deprived students at the CRY (Children's Rights and You) foundation. Taking motivation from these experiences, I decided to start an undergraduate research group at the start of this year. I have been teaching Programming, Biostatistics and Statistics free of charge to underprivileged college students in whatever limited capacity I have. I also encouraged these students to involve themselves in research and have been able to collaborate with them on review articles and book reviews. These experiences have motivated me to become a professor in the future and mentally prepared me for the Ph.D. journey.